# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mraz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setEnabled(True)
        main_window.resize(807, 463)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(102, 140, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 87, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 140, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 87, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 140, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 87, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        main_window.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(7)
        main_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-студент-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        main_window.setToolTipDuration(-9)
        self.tabWidget = QtWidgets.QTabWidget(main_window)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.add_tab = QtWidgets.QWidget()
        self.add_tab.setObjectName("add_tab")
        self.data_tbl = QtWidgets.QTableView(self.add_tab)
        self.data_tbl.setGeometry(QtCore.QRect(0, 0, 381, 331))
        self.data_tbl.setObjectName("data_tbl")
        self.groupBox = QtWidgets.QGroupBox(self.add_tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 340, 361, 101))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.step_slider = QtWidgets.QSlider(self.groupBox)
        self.step_slider.setGeometry(QtCore.QRect(40, 60, 281, 22))
        self.step_slider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.step_slider.setMinimum(1)
        self.step_slider.setMaximum(11)
        self.step_slider.setSingleStep(1)
        self.step_slider.setPageStep(2)
        self.step_slider.setTracking(True)
        self.step_slider.setOrientation(QtCore.Qt.Horizontal)
        self.step_slider.setInvertedAppearance(False)
        self.step_slider.setInvertedControls(True)
        self.step_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.step_slider.setTickInterval(2)
        self.step_slider.setObjectName("step_slider")
        self.depth_text_lbl = QtWidgets.QLabel(self.groupBox)
        self.depth_text_lbl.setGeometry(QtCore.QRect(40, 30, 241, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.depth_text_lbl.setFont(font)
        self.depth_text_lbl.setObjectName("depth_text_lbl")
        self.depth_value_lbl = QtWidgets.QLabel(self.groupBox)
        self.depth_value_lbl.setGeometry(QtCore.QRect(320, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.depth_value_lbl.setFont(font)
        self.depth_value_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_value_lbl.setObjectName("depth_value_lbl")
        self.best_features_te = QtWidgets.QTextEdit(self.add_tab)
        self.best_features_te.setGeometry(QtCore.QRect(390, 20, 181, 311))
        self.best_features_te.setReadOnly(True)
        self.best_features_te.setObjectName("best_features_te")
        self.best_features_lbl = QtWidgets.QLabel(self.add_tab)
        self.best_features_lbl.setGeometry(QtCore.QRect(390, 0, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.best_features_lbl.setFont(font)
        self.best_features_lbl.setObjectName("best_features_lbl")
        self.save_to_file_btn = QtWidgets.QPushButton(self.add_tab)
        self.save_to_file_btn.setGeometry(QtCore.QRect(390, 390, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.save_to_file_btn.setFont(font)
        self.save_to_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons8-save-96.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_to_file_btn.setIcon(icon1)
        self.save_to_file_btn.setIconSize(QtCore.QSize(35, 35))
        self.save_to_file_btn.setCheckable(True)
        self.save_to_file_btn.setObjectName("save_to_file_btn")
        self.clear_btn = QtWidgets.QPushButton(self.add_tab)
        self.clear_btn.setGeometry(QtCore.QRect(390, 340, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clear_btn.setFont(font)
        self.clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons8-trash-96.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon2)
        self.clear_btn.setIconSize(QtCore.QSize(40, 40))
        self.clear_btn.setCheckable(True)
        self.clear_btn.setObjectName("clear_btn")
        self.tabWidget.addTab(self.add_tab, "")
        self.perceptron_tab = QtWidgets.QWidget()
        self.perceptron_tab.setObjectName("perceptron_tab")
        self.percep_params_gb = QtWidgets.QGroupBox(self.perceptron_tab)
        self.percep_params_gb.setGeometry(QtCore.QRect(10, 260, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.percep_params_gb.setFont(font)
        self.percep_params_gb.setFlat(True)
        self.percep_params_gb.setObjectName("percep_params_gb")
        self.max_epochs_lbl = QtWidgets.QLabel(self.percep_params_gb)
        self.max_epochs_lbl.setGeometry(QtCore.QRect(20, 40, 170, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.max_epochs_lbl.setFont(font)
        self.max_epochs_lbl.setObjectName("max_epochs_lbl")
        self.max_epochs_sb = QtWidgets.QSpinBox(self.percep_params_gb)
        self.max_epochs_sb.setGeometry(QtCore.QRect(200, 40, 101, 22))
        self.max_epochs_sb.setMinimum(100)
        self.max_epochs_sb.setMaximum(10000)
        self.max_epochs_sb.setSingleStep(100)
        self.max_epochs_sb.setObjectName("max_epochs_sb")
        self.percep_train_gb = QtWidgets.QGroupBox(self.perceptron_tab)
        self.percep_train_gb.setGeometry(QtCore.QRect(10, 10, 291, 231))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.percep_train_gb.setFont(font)
        self.percep_train_gb.setObjectName("percep_train_gb")
        self.data_perceptron_tbl = QtWidgets.QTableView(self.percep_train_gb)
        self.data_perceptron_tbl.setGeometry(QtCore.QRect(0, 30, 291, 201))
        self.data_perceptron_tbl.setObjectName("data_perceptron_tbl")
        self.percep_output_gb = QtWidgets.QGroupBox(self.perceptron_tab)
        self.percep_output_gb.setGeometry(QtCore.QRect(320, 10, 261, 341))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.percep_output_gb.setFont(font)
        self.percep_output_gb.setFlat(True)
        self.percep_output_gb.setObjectName("percep_output_gb")
        self.weights_matrix_te = QtWidgets.QTextEdit(self.percep_output_gb)
        self.weights_matrix_te.setGeometry(QtCore.QRect(100, 100, 161, 241))
        self.weights_matrix_te.setObjectName("weights_matrix_te")
        self.weights_matrix_lbl = QtWidgets.QLabel(self.percep_output_gb)
        self.weights_matrix_lbl.setGeometry(QtCore.QRect(20, 80, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.weights_matrix_lbl.setFont(font)
        self.weights_matrix_lbl.setObjectName("weights_matrix_lbl")
        self.epochs_num_te = QtWidgets.QTextEdit(self.percep_output_gb)
        self.epochs_num_te.setGeometry(QtCore.QRect(120, 30, 81, 31))
        self.epochs_num_te.setReadOnly(True)
        self.epochs_num_te.setObjectName("epochs_num_te")
        self.epochs_num_lbl = QtWidgets.QLabel(self.percep_output_gb)
        self.epochs_num_lbl.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.epochs_num_lbl.setFont(font)
        self.epochs_num_lbl.setObjectName("epochs_num_lbl")
        self.tabWidget.addTab(self.perceptron_tab, "")
        self.hamming_tab = QtWidgets.QWidget()
        self.hamming_tab.setObjectName("hamming_tab")
        self.haming_train_gb = QtWidgets.QGroupBox(self.hamming_tab)
        self.haming_train_gb.setGeometry(QtCore.QRect(10, 10, 331, 411))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.haming_train_gb.setFont(font)
        self.haming_train_gb.setObjectName("haming_train_gb")
        self.data_haming_tbl = QtWidgets.QTableView(self.haming_train_gb)
        self.data_haming_tbl.setGeometry(QtCore.QRect(0, 30, 331, 381))
        self.data_haming_tbl.setObjectName("data_haming_tbl")
        self.haming_output_gb = QtWidgets.QGroupBox(self.hamming_tab)
        self.haming_output_gb.setGeometry(QtCore.QRect(350, 10, 231, 121))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.haming_output_gb.setFont(font)
        self.haming_output_gb.setFlat(True)
        self.haming_output_gb.setObjectName("haming_output_gb")
        self.label_le = QtWidgets.QLineEdit(self.haming_output_gb)
        self.label_le.setGeometry(QtCore.QRect(110, 40, 113, 20))
        self.label_le.setReadOnly(True)
        self.label_le.setObjectName("label_le")
        self.label_lbl = QtWidgets.QLabel(self.haming_output_gb)
        self.label_lbl.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_lbl.setFont(font)
        self.label_lbl.setObjectName("label_lbl")
        self.tabWidget.addTab(self.hamming_tab, "")
        self.kohonen_tab = QtWidgets.QWidget()
        self.kohonen_tab.setObjectName("kohonen_tab")
        self.kohonen_train_gb = QtWidgets.QGroupBox(self.kohonen_tab)
        self.kohonen_train_gb.setGeometry(QtCore.QRect(10, 10, 211, 331))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.kohonen_train_gb.setFont(font)
        self.kohonen_train_gb.setObjectName("kohonen_train_gb")
        self.data_kohonen_tbl = QtWidgets.QTableView(self.kohonen_train_gb)
        self.data_kohonen_tbl.setGeometry(QtCore.QRect(0, 30, 211, 301))
        self.data_kohonen_tbl.setObjectName("data_kohonen_tbl")
        self.groupBox_2 = QtWidgets.QGroupBox(self.kohonen_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 10, 321, 181))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.kohonen_weights_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.kohonen_weights_le.setGeometry(QtCore.QRect(180, 40, 121, 131))
        self.kohonen_weights_le.setObjectName("kohonen_weights_le")
        self.kohonen_weights_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.kohonen_weights_lbl.setGeometry(QtCore.QRect(30, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.kohonen_weights_lbl.setFont(font)
        self.kohonen_weights_lbl.setObjectName("kohonen_weights_lbl")
        self.tabWidget.addTab(self.kohonen_tab, "")
        self.nsko_tab = QtWidgets.QWidget()
        self.nsko_tab.setObjectName("nsko_tab")
        self.nsko_train_gb = QtWidgets.QGroupBox(self.nsko_tab)
        self.nsko_train_gb.setGeometry(QtCore.QRect(10, 10, 211, 331))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nsko_train_gb.setFont(font)
        self.nsko_train_gb.setObjectName("nsko_train_gb")
        self.data_nsko_tbl = QtWidgets.QTableView(self.nsko_train_gb)
        self.data_nsko_tbl.setGeometry(QtCore.QRect(0, 30, 211, 301))
        self.data_nsko_tbl.setObjectName("data_nsko_tbl")
        self.nsko_params_gb = QtWidgets.QGroupBox(self.nsko_tab)
        self.nsko_params_gb.setGeometry(QtCore.QRect(240, 10, 331, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nsko_params_gb.setFont(font)
        self.nsko_params_gb.setFlat(True)
        self.nsko_params_gb.setObjectName("nsko_params_gb")
        self.nsko_step_lbl = QtWidgets.QLabel(self.nsko_params_gb)
        self.nsko_step_lbl.setGeometry(QtCore.QRect(30, 30, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nsko_step_lbl.setFont(font)
        self.nsko_step_lbl.setObjectName("nsko_step_lbl")
        self.nsko_step_dsb = QtWidgets.QDoubleSpinBox(self.nsko_params_gb)
        self.nsko_step_dsb.setGeometry(QtCore.QRect(170, 30, 62, 22))
        self.nsko_step_dsb.setDecimals(1)
        self.nsko_step_dsb.setMinimum(0.1)
        self.nsko_step_dsb.setMaximum(2.0)
        self.nsko_step_dsb.setSingleStep(0.1)
        self.nsko_step_dsb.setProperty("value", 0.5)
        self.nsko_step_dsb.setObjectName("nsko_step_dsb")
        self.nsko_output_gb = QtWidgets.QGroupBox(self.nsko_tab)
        self.nsko_output_gb.setGeometry(QtCore.QRect(240, 190, 331, 241))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nsko_output_gb.setFont(font)
        self.nsko_output_gb.setFlat(True)
        self.nsko_output_gb.setObjectName("nsko_output_gb")
        self.nsko_weights_te = QtWidgets.QTextEdit(self.nsko_output_gb)
        self.nsko_weights_te.setGeometry(QtCore.QRect(40, 60, 291, 171))
        self.nsko_weights_te.setObjectName("nsko_weights_te")
        self.nsko_weights_lbl = QtWidgets.QLabel(self.nsko_output_gb)
        self.nsko_weights_lbl.setGeometry(QtCore.QRect(30, 30, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nsko_weights_lbl.setFont(font)
        self.nsko_weights_lbl.setObjectName("nsko_weights_lbl")
        self.tabWidget.addTab(self.nsko_tab, "")
        self.habb_tab = QtWidgets.QWidget()
        self.habb_tab.setObjectName("habb_tab")
        self.habb_train_gb = QtWidgets.QGroupBox(self.habb_tab)
        self.habb_train_gb.setGeometry(QtCore.QRect(10, 10, 211, 331))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.habb_train_gb.setFont(font)
        self.habb_train_gb.setObjectName("habb_train_gb")
        self.data_habb_tbl = QtWidgets.QTableView(self.habb_train_gb)
        self.data_habb_tbl.setGeometry(QtCore.QRect(0, 30, 211, 301))
        self.data_habb_tbl.setObjectName("data_habb_tbl")
        self.nsko_params_gb_2 = QtWidgets.QGroupBox(self.habb_tab)
        self.nsko_params_gb_2.setGeometry(QtCore.QRect(230, 10, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nsko_params_gb_2.setFont(font)
        self.nsko_params_gb_2.setFlat(True)
        self.nsko_params_gb_2.setObjectName("nsko_params_gb_2")
        self.max_epochs_habb_lbl = QtWidgets.QLabel(self.nsko_params_gb_2)
        self.max_epochs_habb_lbl.setGeometry(QtCore.QRect(20, 40, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.max_epochs_habb_lbl.setFont(font)
        self.max_epochs_habb_lbl.setObjectName("max_epochs_habb_lbl")
        self.max_epochs_habb_sb = QtWidgets.QSpinBox(self.nsko_params_gb_2)
        self.max_epochs_habb_sb.setGeometry(QtCore.QRect(230, 40, 101, 22))
        self.max_epochs_habb_sb.setMinimum(100)
        self.max_epochs_habb_sb.setMaximum(10000)
        self.max_epochs_habb_sb.setSingleStep(100)
        self.max_epochs_habb_sb.setObjectName("max_epochs_habb_sb")
        self.nsko_output_gb_2 = QtWidgets.QGroupBox(self.nsko_params_gb_2)
        self.nsko_output_gb_2.setGeometry(QtCore.QRect(0, 160, 331, 241))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nsko_output_gb_2.setFont(font)
        self.nsko_output_gb_2.setFlat(True)
        self.nsko_output_gb_2.setObjectName("nsko_output_gb_2")
        self.nsko_weights_te_2 = QtWidgets.QTextEdit(self.nsko_output_gb_2)
        self.nsko_weights_te_2.setGeometry(QtCore.QRect(40, 60, 291, 171))
        self.nsko_weights_te_2.setObjectName("nsko_weights_te_2")
        self.nsko_weights_lbl_2 = QtWidgets.QLabel(self.nsko_output_gb_2)
        self.nsko_weights_lbl_2.setGeometry(QtCore.QRect(30, 30, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nsko_weights_lbl_2.setFont(font)
        self.nsko_weights_lbl_2.setObjectName("nsko_weights_lbl_2")
        self.habb_output_gb = QtWidgets.QGroupBox(self.habb_tab)
        self.habb_output_gb.setGeometry(QtCore.QRect(230, 100, 351, 321))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.habb_output_gb.setFont(font)
        self.habb_output_gb.setFlat(True)
        self.habb_output_gb.setObjectName("habb_output_gb")
        self.habb_weights_te = QtWidgets.QTextEdit(self.habb_output_gb)
        self.habb_weights_te.setGeometry(QtCore.QRect(40, 110, 291, 171))
        self.habb_weights_te.setObjectName("habb_weights_te")
        self.habb_weights_lbl = QtWidgets.QLabel(self.habb_output_gb)
        self.habb_weights_lbl.setGeometry(QtCore.QRect(30, 80, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.habb_weights_lbl.setFont(font)
        self.habb_weights_lbl.setObjectName("habb_weights_lbl")
        self.habb_count_iter_lbl = QtWidgets.QLabel(self.habb_output_gb)
        self.habb_count_iter_lbl.setGeometry(QtCore.QRect(30, 40, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.habb_count_iter_lbl.setFont(font)
        self.habb_count_iter_lbl.setObjectName("habb_count_iter_lbl")
        self.habb_count_iter_le = QtWidgets.QLineEdit(self.habb_output_gb)
        self.habb_count_iter_le.setGeometry(QtCore.QRect(180, 40, 81, 20))
        self.habb_count_iter_le.setReadOnly(True)
        self.habb_count_iter_le.setPlaceholderText("")
        self.habb_count_iter_le.setObjectName("habb_count_iter_le")
        self.tabWidget.addTab(self.habb_tab, "")
        self.kopa_tab = QtWidgets.QWidget()
        self.kopa_tab.setObjectName("kopa_tab")
        self.kopa_train_gb = QtWidgets.QGroupBox(self.kopa_tab)
        self.kopa_train_gb.setGeometry(QtCore.QRect(10, 10, 211, 331))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.kopa_train_gb.setFont(font)
        self.kopa_train_gb.setObjectName("kopa_train_gb")
        self.data_kopa_tbl = QtWidgets.QTableView(self.kopa_train_gb)
        self.data_kopa_tbl.setGeometry(QtCore.QRect(0, 30, 211, 301))
        self.data_kopa_tbl.setObjectName("data_kopa_tbl")
        self.tabWidget.addTab(self.kopa_tab, "")
        self.load_data_btn = QtWidgets.QPushButton(main_window)
        self.load_data_btn.setGeometry(QtCore.QRect(600, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        font.setPointSize(11)
        self.load_data_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons8-downloads-folder-96.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_data_btn.setIcon(icon3)
        self.load_data_btn.setIconSize(QtCore.QSize(40, 40))
        self.load_data_btn.setCheckable(True)
        self.load_data_btn.setFlat(False)
        self.load_data_btn.setObjectName("load_data_btn")
        self.fit_btn = QtWidgets.QPushButton(main_window)
        self.fit_btn.setGeometry(QtCore.QRect(600, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        font.setPointSize(11)
        self.fit_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons8-play-30.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fit_btn.setIcon(icon4)
        self.fit_btn.setIconSize(QtCore.QSize(40, 40))
        self.fit_btn.setCheckable(True)
        self.fit_btn.setObjectName("fit_btn")
        self.fit_btn.raise_()
        self.tabWidget.raise_()
        self.load_data_btn.raise_()

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Примеры работы алгоритмов"))
        self.groupBox.setTitle(_translate("main_window", "Параметры алгоритма"))
        self.depth_text_lbl.setText(_translate("main_window", "Глубина просматривания вперед (d) :"))
        self.depth_value_lbl.setText(_translate("main_window", "1"))
        self.best_features_te.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.best_features_lbl.setText(_translate("main_window", "Выделенные признаки"))
        self.save_to_file_btn.setText(_translate("main_window", "Сохранить признаки"))
        self.clear_btn.setText(_translate("main_window", "Удалить содержимое"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_tab), _translate("main_window", "Add "))
        self.percep_params_gb.setTitle(_translate("main_window", "Параметры алгоритма"))
        self.max_epochs_lbl.setText(_translate("main_window", "Максимальное количество эпох:"))
        self.percep_train_gb.setTitle(_translate("main_window", "Обучающая выборка"))
        self.percep_output_gb.setTitle(_translate("main_window", "Вывод алгоритма"))
        self.weights_matrix_lbl.setText(_translate("main_window", "Матрица весов:"))
        self.epochs_num_te.setPlaceholderText(_translate("main_window", "0"))
        self.epochs_num_lbl.setText(_translate("main_window", "Количество эпох:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.perceptron_tab), _translate("main_window", "Персептрон"))
        self.haming_train_gb.setTitle(_translate("main_window", "Эталонные вектора и вектор для классификации"))
        self.haming_output_gb.setTitle(_translate("main_window", "Вывод алгоритма"))
        self.label_le.setPlaceholderText(_translate("main_window", "-1"))
        self.label_lbl.setText(_translate("main_window", "Номер класса:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hamming_tab), _translate("main_window", "Алгоритм Хемминга"))
        self.kohonen_train_gb.setTitle(_translate("main_window", "Обучающая выборка"))
        self.groupBox_2.setTitle(_translate("main_window", "Вывод алгоритма:"))
        self.kohonen_weights_lbl.setText(_translate("main_window", "Матрица весов:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kohonen_tab), _translate("main_window", "Алгоритм Кохонена"))
        self.nsko_train_gb.setTitle(_translate("main_window", "Обучающая выборка"))
        self.nsko_params_gb.setTitle(_translate("main_window", "Параметры алгоритма"))
        self.nsko_step_lbl.setText(_translate("main_window", "Величина шага (h):"))
        self.nsko_output_gb.setTitle(_translate("main_window", "Вывод алгоритма"))
        self.nsko_weights_lbl.setText(_translate("main_window", "Матрица весов:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nsko_tab), _translate("main_window", "НСКО"))
        self.habb_train_gb.setTitle(_translate("main_window", "Обучающая выборка"))
        self.nsko_params_gb_2.setTitle(_translate("main_window", "Параметры алгоритма"))
        self.max_epochs_habb_lbl.setText(_translate("main_window", "Максимальное количество итераций:"))
        self.nsko_output_gb_2.setTitle(_translate("main_window", "Вывод алгоритма"))
        self.nsko_weights_lbl_2.setText(_translate("main_window", "Матрица весов:"))
        self.habb_output_gb.setTitle(_translate("main_window", "Вывод алгоритма"))
        self.habb_weights_lbl.setText(_translate("main_window", "Матрица весов:"))
        self.habb_count_iter_lbl.setText(_translate("main_window", "Количество итераций:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.habb_tab), _translate("main_window", "Алгоритм Хебба"))
        self.kopa_train_gb.setTitle(_translate("main_window", "Обучающая выборка"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kopa_tab), _translate("main_window", "КОРА"))
        self.load_data_btn.setText(_translate("main_window", "Загрузить данные"))
        self.fit_btn.setText(_translate("main_window", "Обучить модель"))

